#SpringBoot启动端口和项目路径
server:
  port: 8080
  context-path: /

#SpringMVC中JSP视图配置
spring:
  application:
    name: sys-provider
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #启用开发模式
  #profiles:
  #active: dev
  http:
    encoding:
      force: true		#是否在HTTP请求和响应上强制编码到配置的字符集。
      charset: UTF-8	#HTTP 请求和响应的字符集。如果未明确设置，则添加到“Content-Type”标头。

  #datasource
  #spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000

#mybatis
mybatis:
  mapper-locations: classpath:mysqlmapping/*Mapper.xml
  type-aliases-package: com.mytest.sys.pojo

#pagehelper分页插件配置（可以不配）
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#日志配置 Spring Boot默认会用Logback来记录日志，并用INFO级别输出到控制台
logging:
  #如果是默认文件名logback-spring.xml，则不需要配置
  #config: classpath:logback-spring.xml
  #使用mybatis的时候，sql语句是debug下才会打印，而这里我们只配置了info，所以想要查看sql语句的话
  #单独给dao下目录配置debug模式，代码如下，这样配置sql语句会打印，其他还是正常info级别，推荐用logger标签
  level:
    com:
      demo:
        springboot:
          dao: debug
  #  org:
  #    mybatis: debug
  #    springframework:
  #      data:
  #        mybatis: debug

eureka:
  client:   #客户端注册进eureka服务列表内
    service-url:
      #单机注册如下
      defaultZone: http://localhost:7001/eureka
      #集群注册如下
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:  #会在eureka界面应用状态中显示如下名称，不配置就是ip地址
    #instance-id: sys-provider${server.port}
    preferIpAddress: true #当应用程序向eureka注册时，它使用其IP地址而不是其主机名。
